kind: Secret
apiVersion: v1
metadata:
  name: my-basic-auth-secret-2
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://EXT97929:<PAT>@github.com